import {test,expect} from '@playwright/test';
test('eight illustrated Pino scenes connect real play and reading without fabricating memories',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/にじの道/}).click();await page.getByRole('button',{name:'みどり',exact:true}).click();await page.getByRole('button',{name:'この時間を、記憶に'}).click();await page.getByRole('button',{name:'ピノのおはなしを読む',exact:true}).click();
 const book=page.getByRole('article',{name:'ふたつのいろ、ひとつのにじ',exact:true});await expect(book).toBeVisible();await expect(book.getByText('1 / 8', {exact:true})).toBeVisible();
 for(let i=0;i<8;i++){await expect(book.getByText(`${i+1} / 8`,{exact:true})).toBeVisible();expect(await book.locator('.friendship-picture img').evaluate(async(e:HTMLImageElement)=>{await e.decode();return e.naturalWidth===1536&&e.naturalHeight===1024;})).toBe(true);if(i===3)await expect(book.locator('.friendship-text')).toContainText('ここにいてもいいのかな');if(i<7)await book.getByRole('button',{name:'おはなしの次のページ'}).click();}
 await expect(book.locator('.friendship-text')).toContainText('返事を待ってから');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('mocomo.guest.memories.v1')!).length)).toBe(1);
 await book.getByRole('button',{name:'ピノと、色の雲であそぶ'}).click();await expect(page.locator('.pino-room')).toBeVisible();await page.getByRole('button',{name:/えほん BOOK/}).click();await page.getByRole('button',{name:/モコモとピノのおはなし/}).click();await expect(page.getByText('8 / 8',{exact:true})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:/えほん BOOK/}).click();await page.getByRole('button',{name:/モコモとピノのおはなし/}).click();await expect(page.getByText('8 / 8',{exact:true})).toBeVisible();await page.getByRole('button',{name:'おはなしの4ページへ'}).click();
 await page.getByRole('button',{name:'絵本にひたる · 大きく読む'}).click();await page.setViewportSize({width:844,height:390});const dialog=page.getByRole('dialog');await expect(dialog.getByText('4 / 8',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'BGMをきく'}).click();await expect(dialog.getByRole('button',{name:'BGMをとめる'})).toHaveAttribute('aria-pressed','true');await dialog.getByRole('button',{name:'大きな絵本の次のページ'}).click();await expect(dialog.getByText('5 / 8',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/pino-book-landscape.png'});await dialog.getByRole('button',{name:'絵本にもどる',exact:true}).click();
 for(const width of [320,390,760,1440]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 expect(errors).toEqual([]);
});
