import {test,expect} from '@playwright/test';
test('five activities persist memories, grow world, and make a real book',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');
 await page.getByRole('button',{name:'もこもに、こんにちは'}).click();await expect(page.getByRole('status')).toContainText('この端末に記憶を保存');
 await page.getByRole('button',{name:/もこもこジャンプ/}).click();await page.getByRole('button',{name:'もこもとジャンプ'}).click();await page.getByRole('button',{name:'この時間を、記憶に'}).click();await page.getByRole('button',{name:'雲の世界へ'}).click();
 await page.getByRole('button',{name:/ひみつさがし/}).click();await page.getByRole('button',{name:'雲1をさがす'}).click();await expect(page.getByRole('button',{name:'この時間を、記憶に'})).toBeDisabled();await page.getByRole('button',{name:'雲2をさがす'}).click();await page.getByRole('button',{name:'この時間を、記憶に'}).click();await page.getByRole('button',{name:'雲の世界へ'}).click();
 await page.getByRole('button',{name:/にじの道/}).click();await page.getByRole('button',{name:'そらいろ',exact:true}).click();await page.getByRole('button',{name:'この時間を、記憶に'}).click();await page.getByRole('button',{name:'雲の世界へ'}).click();
 await page.getByRole('button',{name:/もぐもぐキッチン/}).click();await page.getByRole('button',{name:/おにぎり/}).click();await page.getByRole('button',{name:'お皿にのせる'}).click();await page.getByRole('button',{name:'いっしょに、いただきます'}).click();await page.getByRole('button',{name:'この時間を、記憶に'}).click();await page.getByRole('button',{name:'雲の世界へ'}).click();
 await page.getByRole('button',{name:/ほっとタイム/}).click();await page.getByRole('button',{name:'ひと休みを、記憶に'}).click();await page.getByRole('button',{name:'雲の世界へ'}).click();
 await page.reload();await page.getByRole('button',{name:/せかい WORLD/}).click();await expect(page.getByText('虹の道 1')).toBeVisible();await expect(page.getByText('ひと休み 1')).toBeVisible();
 await page.getByRole('button',{name:/えほん BOOK/}).click();await expect(page.getByText('1 / 6')).toBeVisible();await page.getByRole('button',{name:'次のページ'}).click();await expect(page.getByText('2 / 6')).toBeVisible();
 expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/mocomo-mobile.png',fullPage:true});
});
test('family gate and quiet mode persist, with no horizontal overflow',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/おうち FAMILY/}).click();await expect(page.getByLabel('保護者のメールアドレス')).toHaveCount(0);await page.getByRole('button',{name:'私は保護者です'}).click();if(await page.getByText('クラウド保存は準備中です。端末でのお試しは使えます。').count()){await expect(page.getByLabel('保護者のメールアドレス')).toHaveCount(0);}else{await expect(page.getByLabel('保護者のメールアドレス')).toBeVisible();}await page.getByRole('switch').click();await expect(page.getByRole('switch')).toHaveAttribute('aria-checked','true');await page.reload();await page.getByRole('button',{name:/おうち FAMILY/}).click();await page.getByRole('button',{name:'私は保護者です'}).click();await expect(page.getByRole('switch')).toHaveAttribute('aria-checked','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
test('desktop home renders all navigation and activities',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/');await expect(page.getByRole('heading',{level:1})).toContainText('きょうも');await expect(page.getByRole('button',{name:/この時間を、記憶に/})).toHaveCount(0);await expect(page.locator('.game-card')).toHaveCount(5);await page.screenshot({path:'test-results/mocomo-desktop.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);});
